from fpdf import FPDF
import os
from backend.config import settings

class SummarizerrPDF(FPDF):
    def header(self):
        # Draw top navbar decoration
        self.set_fill_color(79, 70, 229) # Indigo #4f46e5
        self.rect(0, 0, 210, 8, 'F')
        
        self.ln(5)
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(79, 70, 229)
        self.cell(0, 10, 'SUMMARIZERR REPORT', border=False, new_x="LMARGIN", new_y="NEXT", align='L')
        
        # Draw a thin horizontal separator
        self.set_draw_color(229, 231, 235) # Light gray
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(8)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(156, 163, 175) # Cool gray
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Summarizerr AI', align='C')

def generate_pdf_report(doc_name: str, summary: str, stats: dict, charts: list[str], output_path: str):
    """
    Generates a structured PDF document report containing file summary, stats, and charts.
    """
    pdf = SummarizerrPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(31, 41, 55) # Dark gray #1f2937

    # File info section
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, "1. File Metadata Information", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', '', 10)
    pdf.ln(2)
    
    # Metadata details
    file_type = stats.get("file_type", "").upper()
    text_stats = stats.get("text_stats", {})
    
    pdf.cell(40, 6, "File Name:", border=0)
    pdf.cell(0, 6, doc_name, border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(40, 6, "File Format:", border=0)
    pdf.cell(0, 6, file_type, border=0, new_x="LMARGIN", new_y="NEXT")
    
    if text_stats:
        pdf.cell(40, 6, "Word Count:", border=0)
        pdf.cell(0, 6, f"{text_stats.get('word_count', 0)} words", border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.cell(40, 6, "Character Count:", border=0)
        pdf.cell(0, 6, f"{text_stats.get('char_count', 0)} chars", border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.cell(40, 6, "Estimated Reading Time:", border=0)
        pdf.cell(0, 6, f"{text_stats.get('reading_time_minutes', 0)} minutes", border=0, new_x="LMARGIN", new_y="NEXT")

    if stats.get("is_tabular") and "tabular_stats" in stats:
        t_stats = stats["tabular_stats"]
        pdf.cell(40, 6, "Tabular Dimensions:", border=0)
        pdf.cell(0, 6, f"{t_stats.get('row_count', 0)} rows x {t_stats.get('column_count', 0)} columns", border=0, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # 2. Document Summary Section
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, "2. AI Generated Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', '', 10)
    pdf.ln(2)

    # Render summary markdown elements
    if summary:
        for line in summary.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(3)
                continue
                
            if line.startswith("###"):
                pdf.set_font('helvetica', 'B', 10)
                pdf.set_text_color(79, 70, 229)
                pdf.cell(0, 6, line.replace("###", "").strip(), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font('helvetica', '', 10)
                pdf.set_text_color(31, 41, 55)
            elif line.startswith("##"):
                pdf.set_font('helvetica', 'B', 11)
                pdf.set_text_color(79, 70, 229)
                pdf.cell(0, 8, line.replace("##", "").strip(), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font('helvetica', '', 10)
                pdf.set_text_color(31, 41, 55)
            elif line.startswith("#"):
                pdf.set_font('helvetica', 'B', 13)
                pdf.set_text_color(79, 70, 229)
                pdf.cell(0, 10, line.replace("#", "").strip(), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font('helvetica', '', 10)
                pdf.set_text_color(31, 41, 55)
            elif line.startswith("-") or line.startswith("*"):
                # Bullet list point
                clean_bullet = line[1:].strip()
                # Clean simple bold markdown from line **text** -> text
                clean_bullet = clean_bullet.replace("**", "").replace("*", "")
                
                pdf.set_x(15)
                # Bullet point symbol (draw tiny square or circle or standard text bullet)
                pdf.cell(4, 6, chr(149), border=0)
                pdf.multi_cell(0, 6, clean_bullet, new_x="LMARGIN", new_y="NEXT")
            else:
                clean_line = line.replace("**", "").replace("*", "")
                pdf.multi_cell(0, 6, clean_line, new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 6, "No summary available for this document.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # 3. Add Charts Section if available
    if charts:
        pdf.add_page()
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 8, "3. Visualizations & Analytical Charts", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('helvetica', '', 10)
        pdf.ln(5)
        
        charts_dir = os.path.join(settings.UPLOAD_DIR, "charts")
        for filename in charts:
            chart_path = os.path.join(charts_dir, filename)
            if os.path.exists(chart_path):
                # Center-plot the chart
                pdf.image(chart_path, x=15, w=180)
                pdf.ln(5)

    # Create the output parent directories if missing
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
